module.exports = {
  desc: 'tells you the truth',
  execute(message, command) {
    var truths = `awesome
      fascinating
      incredible
      marvelous
      prodigious
      shocking
      stunning
      surprising
      unbelievable
      wonderful
      astounding
      bewildering
      breathtaking
      extraordinary
      impressive
      marvelous
      miraculous
      spectacular
      staggering
      startling
      striking
      stunning
      stupefying
      stupendous
      wonderful
      wondrous
      amazing
      astonishing
      awesome
      breathtaking
      grand
      impressive
      majestic
      mind-blowing
      remarkable
      stunning
      wonderful
      amazing
      astonishing
      astounding
      awe-inspiring
      awesome
      extraordinary
      fabulous
      glorious
      great
      prodigious
      superhuman
      unreal
      wonderful
      amazing
      astonishing
      breathtaking
      mind-blowing
      spectacular
      staggering
      startling
      stunning
      stupendous
      surprising
      wonderful
      amazing
      astonishing
      astounding
      breathtaking
      daring
      fabulous
      fantastic
      grand
      magnificent
      marked
      marvelous
      miraculous
      prodigious
      remarkable
      sensational
      splendid
      staggering
      striking
      stunning
      stupendous
      theatrical
      thrilling
      wondrous`
    var truth = truths.split("\n")[Math.floor(Math.random() * truths.split("\n").length)];
    message.channel.send(truth);
  }
}
